### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by mauritsvanrees** [collective/collective.restapi.pam#7]
Hi @erral. You requested to install Travis CI in the collective, but it is already installed. Maybe someone already did this meanwhile. It seemed to be a request for collective.restapi.pam and collective.restapi.linguaplone. I see links to Travis status on both packages. Is anything still needed?

**Comment by erral** [comment]
Thanks... eh... I was trying to fix Travis on friday and perhaps I clicked somewhere where I shouldn't. don't worry.
